# Generated by Django 5.1.dev20240415161635 on 2025-01-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_answers_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answers',
        ),
    ]
