# Generated by Django 5.1.dev20240415161635 on 2025-01-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_answer_question_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=255)),
                ('answers', models.CharField(max_length=255)),
            ],
        ),
    ]
